FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    aiomqtt \
    python-dotenv \
    pydantic-settings \
    rpi-lgpio

COPY src/gpio_controller.py .

CMD ["python", "gpio_controller.py"]
